name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: ./CI/build/configureDocker.sh && docker build -t blackwalker01/dl_build CI/build/. --tag dark-logic-image:$(date +%s)
      
